[package]
name = "convert"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.13", features = ["derive"] }
itertools = "0.13.0"
json_comments = "0.2.2"
serde = "1.0.204"
serde_derive = "1.0.204"
serde_json = "1.0.122"
